# Generated by Django 3.1 on 2020-08-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='quote',
            field=models.CharField(default='Just another cook', max_length=50),
        ),
    ]
