# Generated by Django 3.1 on 2020-08-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_author_quote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('title',)},
        ),
    ]
